server:
  port: 5002
spring:
  datasource:
    driver-class-name:  oracle.jdbc.OracleDriver
    url:  jdbc:oracle:thin:@localhost:1521/XE
    username: nxt
    password: nxt
  jpa: 
    generate-ddl: true 
    properties:
      hibernate:
        format_sql: true
        show_sql: true 
        ddl-auto: update
        dialect: org.hibernate.dialect.Oracle10gDialect
